--- 
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: '{{ .Values.guest.name }}'
  namespace: '{{ .Values.host.namespace }}'
spec:
  gateways:
  - istio-system/istio-gateway
  hosts:
  - '{{ include "vcluster.sniHost" . }}'
  tls:
  - match:
    - port: 443
      sniHosts:
      - '{{ include "vcluster.sniHost" . }}'
    route:
    - destination:
        host: '{{ include "vcluster.internalName" . }}'
        port:
          number: 443
