{{ if .Values.hooks.argocd_enrolment.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: argocd-vcluster-enrolment-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: argocd-vcluster-enrolment
        image: busybox
        command: ["echo",  "hello {{ .Values.guest.name }} on {{ .Values.host.name }}"]
      restartPolicy: Never
  backoffLimit: 1
{{ end }}
