{{ if .Values.hooks.argocd_enrolment.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: argocd-vcluster-enrolment-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: argocd-vcluster-enrolment
        image: argocd-vcluster-enrolment:{{ .Values.hooks.argocd_enrolment.tag }}
        args:
          - -action
          - add
          - -cluster
          - {{ .Values.host.name }}
          - -vcluster
          - {{ .values.guest.name }}
          - -vcluster-namespace
          - {{ .Values.host.namespace }}
          - -vcluster-secret-name
          - {{ .Values.host.name }}-{{ .Values.guest.name }}
      restartPolicy: Never
  backoffLimit: 1
{{ end }}
